### ISSUE TITLE
Iron Golem not spawing in Iron farm

### ISSUE THREAD

**Issue by C00PMEISTER** [Globox1997/AdditionZ#12]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.23

### Mod Version

1.20

### Describe the Issue

Built an iron farm and Iron Golems were not spawning, built a different iron farm and still not spawning, Disabled mod and now they are spawning instantly.

Tested twice.

### latest.log

None

### Do you use any other mods except the required ones?

Yes

**Comment by Globox1997** [comment]
There is a config especially to nerf iron golem farms called max_iron_golem_villager_spawn.
Turn it to 0 to disable it (fixed with [https://github.com/Globox1997/AdditionZ/commit/9da89f00863f50abfaed3945868cef691ca6cb55](https://github.com/Globox1997/AdditionZ/commit/9da89f00863f50abfaed3945868cef691ca6cb55))
